### ISSUE TITLE
Choice of License

### ISSUE THREAD

**Issue by goerz** [qucontrol/openquad#2]
Are you sure you want to release this under GPLv3? Since the GPL includes provisions against linking, that would imply that only GPLv3 projects can import (!) openquad. Although it's not clear whether that is really enforceable: https://tech.popdata.org/the-gpl-license-and-linking-still-unclear-after-30-years/

At least, you might consider the LGPL, or, if you want anyone in a company (let's say Qruise) to use this, you'd probably have to switch to BSD or MIT.

**Comment by ablech** [comment]
Hi Michael, thanks for bringing this up! I am indeed thinking about switching from GPL to a weaker copyleft license, LGPL or rather MPL, with the next release.

To motivate:
I'd like to make sure that improvements of the library remain open source. I also would like openquad to be available for any kind of scientific use. But I am still deliberating about profit-oriented use in general. I plan to counsel with FU's legal office once they return from summer break and wanted decide after that.

We started with the GPL because I thought it easier to switch to a more permissive license later than the other way around.
As far as I understand, the license basically only matters if you start distributing the code. So using openquad for private projects should be possible anyway.

**Comment by goerz** [comment]
> As far as I understand, the license basically only matters if you start distributing the code.

That part isn't quite true, at least not if you follow the (questionable) legal interpretation of the FSF. If you use GPL for a *library*, any project just *using* the library as a dependency would also have to be under the GPL. So that makes the library basically unusable.

> I also would like openquad to be available for any kind of scientific use

If that's the goal, and you're not ideologically tied to the ideas of the GPL, use the most permissive license you can find (that is, MIT/BSD or something very similar).

**Comment by ablech** [comment]
> > As far as I understand, the license basically only matters if you start distributing the code.
> 
> That part isn't quite true

Yes, you are right. I just now realize that I might not have been clear. I mean that GPL restrictions only apply, once the *code that uses openquad* is being distributed. 

> If [...] you're not ideologically tied to the ideas of the GPL, use the most permissive license you can find (that is, MIT/BSD or something very similar).

I do see the point of the GPL, but I do not quite agree with the level of restrictiveness that this ideology implies for GPL libraries that merely being linked.

On the other hand, these permissive licenses do not quite capture:

> > I'd like to make sure that improvements of the library remain open source

Or would you disagree?

**Comment by goerz** [comment]
> On the other hand, these permissive licenses do not quite capture:
> 
>> I'd like to make sure that improvements of the library remain open source

Right… you just have to use the LGPL instead of the GPL. Basically, the GPL should never be used for libraries unless one holds the extreme position that all software should be GPL, which isn't very realistic (but it's what the FSF believes).

> And a weak copyleft should not be a problem for companies using openquad, should'nt it?

The GPL would definitely be a problem (not just for companies, but for anyone not exclusively using the GPL). The LGPL should be fine, although companies might not actively want to contribute to a LGPL library. A weak copyleft license like BSD and MIT would be fine with most companies, but doesn't guarantee that modified versions of the library would be open source.

Of course, you can always release it publicly under LGPL and then also release it to some specific company under some other license, if that ever comes up.

**Comment by ablech** [comment]
> Of course, you can always release it publicly under LGPL and then also release it to some specific company under some other license, if that ever comes up.

Yes, I was thinking about something like that.

In any case, thank you very much for your input!

**Comment by ablech** [comment]
After habing thought about and after the discussion with FU's legal office, we will change the license to the [Mozilla Public License](https://www.mozilla.org/en-US/MPL/). It is similar in spirit as the LGPL, but does not follow the ideology of the FSF. In comparison it rather encourages proprietary use - or at least tries to avoid obstacles. So I hope, that this will protect the open source nature of the project while at the same time not setting back companies to use it or even contribute.

For the record: @RaoulEb agreed to the change of the license.

**Comment by ablech** [comment]
Closed by 026d80d
